//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CtrlInterfaces
{
    [Serializable]
    public class PosTargetMsg : Message
    {
        public const string k_RosMessageName = "ctrl_interfaces/PosTarget";
        public override string RosMessageName => k_RosMessageName;

        public double pos_x;
        public double pos_y;
        public double pos_z;
        public double rot_x;
        public double rot_y;
        public double rot_z;
        public double rot_w;

        public PosTargetMsg()
        {
            this.pos_x = 0.0;
            this.pos_y = 0.0;
            this.pos_z = 0.0;
            this.rot_x = 0.0;
            this.rot_y = 0.0;
            this.rot_z = 0.0;
            this.rot_w = 0.0;
        }

        public PosTargetMsg(double pos_x, double pos_y, double pos_z, double rot_x, double rot_y, double rot_z, double rot_w)
        {
            this.pos_x = pos_x;
            this.pos_y = pos_y;
            this.pos_z = pos_z;
            this.rot_x = rot_x;
            this.rot_y = rot_y;
            this.rot_z = rot_z;
            this.rot_w = rot_w;
        }

        public static PosTargetMsg Deserialize(MessageDeserializer deserializer) => new PosTargetMsg(deserializer);

        private PosTargetMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pos_x);
            deserializer.Read(out this.pos_y);
            deserializer.Read(out this.pos_z);
            deserializer.Read(out this.rot_x);
            deserializer.Read(out this.rot_y);
            deserializer.Read(out this.rot_z);
            deserializer.Read(out this.rot_w);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos_x);
            serializer.Write(this.pos_y);
            serializer.Write(this.pos_z);
            serializer.Write(this.rot_x);
            serializer.Write(this.rot_y);
            serializer.Write(this.rot_z);
            serializer.Write(this.rot_w);
        }

        public override string ToString()
        {
            return "PosTargetMsg: " +
            "\npos_x: " + pos_x.ToString() +
            "\npos_y: " + pos_y.ToString() +
            "\npos_z: " + pos_z.ToString() +
            "\nrot_x: " + rot_x.ToString() +
            "\nrot_y: " + rot_y.ToString() +
            "\nrot_z: " + rot_z.ToString() +
            "\nrot_w: " + rot_w.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
