//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CtrlInterfaces
{
    [Serializable]
    public class UnityCommandMsg : Message
    {
        public const string k_RosMessageName = "ctrl_interfaces/UnityCommand";
        public override string RosMessageName => k_RosMessageName;

        public string command;

        public UnityCommandMsg()
        {
            this.command = "";
        }

        public UnityCommandMsg(string command)
        {
            this.command = command;
        }

        public static UnityCommandMsg Deserialize(MessageDeserializer deserializer) => new UnityCommandMsg(deserializer);

        private UnityCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
        }

        public override string ToString()
        {
            return "UnityCommandMsg: " +
            "\ncommand: " + command.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
